# Generated by Django 4.2.15 on 2025-04-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0035_update_trace_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeycloakConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('url', models.CharField(blank=True, help_text="URL de l'application Keycloak", max_length=128, verbose_name='URL')),
                ('username', models.CharField(blank=True, max_length=128, verbose_name='Utilisateur')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Mot de passe')),
                ('client_id', models.CharField(blank=True, max_length=128, verbose_name='id client')),
                ('users', models.ManyToManyField(blank=True, related_name='+', related_query_name='+', to='base.apiuser')),
            ],
            options={
                'verbose_name': 'Connecteur Keycloak',
            },
        ),
    ]
